# Ansible playbook for setting up passwordless ssh

# - name: Print all variables for each remote device
#   debug: 
#         var: hostvars[groups['tag_HadoopRole_master'][0]]['hadoop_pub_key']['content']

- name: Add passphrase-less public key to authorized_keys on hadoop nodes
  authorized_key:
    user: ubuntu
    state: present
    key: "{{ hostvars[groups['tag_HadoopRole_master'][0]]['hadoop_pub_key']['content'] | b64decode }}"