# Ansible script for configuring and starting a Hadoop cluster

---
- hosts: tag_HadoopRole_master
  roles: 
    - hadoop-master
    - hadoop-all

- hosts: tag_HadoopRole_worker
  roles: 
    - hadoop-all
    - hadoop-worker