# Ansible playbook for gathering current EC2 facts from AWS
# using the ec2_instance_facts module
---
- hosts: localhost
  tasks:
  - name: Gather hadoop cluster's facts
    ec2_instance_facts:
      aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
      aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
      region: "{{ lookup('env', 'AWS_REGION') }}"  
      filters:
        instance-state-name: running
        "tag:Cluster": hadoop
    register: ec2_cluster_facts
  - name: print hadoop facts
    debug: 
      var: ec2_cluster_facts
